name: Build Java App

on:
  workflow_dispatch:
  #push:    # NOTE: Will not work with inputs. No environment selection would be possible using this method.
  #  branches: [ main ]
    inputs:
      environment:
        type: string
        required: true
        description: "dev | stag | prod"

permissions:
  id-token: write
  contents: read

env:
  WORKDIR: "./jvx"

jobs:
  jvx-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390157243794:role/iac-aws-oidcRole-app-jvx
          aws-region: eu-west-2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # NOTE: Build jvx
      - name: Lint
        working-directory: ${{ env.WORKDIR }}    
        run: mvn checkstyle:check

      - name: Test
        working-directory: ${{ env.WORKDIR }}        
        run: mvn test

      - name: Build
        working-directory: ${{ env.WORKDIR }}
        run: mvn package -DskipTests

      - name: Empty S3 bucket from old artifacts # OPTIMIZE: Leave last 5 artifacts for roll back?
        working-directory: ${{ env.WORKDIR }}
        run: aws s3 rm s3://rk-artifact --recursive
     
      - name: Upload artifact to S3
        working-directory: ${{ env.WORKDIR }}
        run: aws s3 cp target/myapp.jar s3://rk-artifact/jvx-${{ github.sha }}.jar

      - name: Update version in SSM
        run: |
          aws ssm put-parameter \
            --name "/jvx/version" \
            --value "${{ github.sha }}" \
            --type String \
            --overwrite

      # NOTE: Refresh ASG
      - name: Set ASG name
        id: asg
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "ASG_NAME=operations-dev-jvx-asg" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "stag" ]; then
            echo "ASG_NAME=operations-stag-jvx-asg" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            echo "ASG_NAME=operations-prod-jvx-asg" >> $GITHUB_ENV
          else
            echo "Unknown environment"
            exit 1
          fi


      - name: Trigger ASG Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
          --auto-scaling-group-name $ASG_NAME \
          --preferences '{"MinHealthyPercentage": 90}'
