name: Build Java App

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  WORKDIR: "./jvx"

jobs:
  jvx-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::390157243794:role/iac-aws-oidcRole-app-jvx-artifacts
          aws-region: eu-west-2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # NOTE: Build jvx
      - name: Lint
        working-directory: ${{ env.WORKDIR }}    
        run: mvn checkstyle:check

      - name: Test
        working-directory: ${{ env.WORKDIR }}        
        run: mvn test

      - name: Build
        working-directory: ${{ env.WORKDIR }}
        run: mvn package -DskipTests

      - name: Upload artifact to S3
        working-directory: ${{ env.WORKDIR }}
        run: aws s3 cp target/myapp.jar s3://rk-artifact/jvx-${{ github.sha }}.jar

      - name: Update version in SSM
        run: |
          aws ssm put-parameter \
            --name "/jvx/version" \
            --value "${{ github.sha }}" \
            --type String \
            --overwrite

      # NOTE: Refresh ASG
      - name: Trigger ASG Instance Refresh
        run: |
          aws autoscaling start-instance-refresh \
          --auto-scaling-group-name my_asg \
          --preferences '{"MinHealthyPercentage": 90}'
